server:
  port: 10000



spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    data-source-one:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/mydb?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      username: root
      password: root
    data-source-two:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/local?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      username: root
      password: root



mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: multipart.datasource.entity